Repository group-extends-ud/calculator, pull requests merged in 2023-11, with the labels that each got.

#16 Mejorando interfaz, ensamble de gui con código, corrección de bugs en el código y Launcher #10 #12 #13
  .idea/uiDesigner.xml
  modelos/precedenceRules.txt
  src/Calculator.java
  src/Expression.java
  src/TerminalExpression.java
  src/control/Control.java
  src/control/Launcher.java
  src/model/Calculator.java
  src/model/Context.java
  src/model/Expression.java
  src/model/Interpreter.properties
  src/model/NonTerminalExpression.java
  src/model/Stack.java
  src/model/TerminalExpression.java
  src/model/ws_ftp.log
  src/service/Extension.java
  src/service/GraphicService.java
  src/service/ResourceService.java
  src/vista/Boton.java
  src/vista/ButtonHandler.java
  src/vista/Ventana.java
Labels: Bug, GUI, Código

#17 Se agregan las operaciones requeridas por el profesor, se limpia un poco el código
  .idea/misc.xml
  src/model/Calculator.java
  src/model/Context.java
  src/model/NonTerminalExpression.java
  src/model/Stack.java
  src/model/TerminalExpression.java
  src/vista/ButtonHandler.java
  src/vista/Ventana.java
Labels: Código

#29 Versión final sustentada al profesor Diosa
  .idea/misc.xml
  modelos/Interpretador.qea
  src/control/AppController.java
  src/model/Calculator.java
  src/model/Context.java
  src/model/NonTerminalExpression.java
  src/model/Stack.java
  src/service/ResourceService.java
  src/vista/Boton.java
  src/vista/Ventana.java
Labels: Modelado, Código
